package parser.constants;

public interface Constants {

	int LG_REGC = 0xCD;
	int LG_REG = 0xCA;
	int LG_VOI = 0x1CC;
	int LG_FLU = 8 * 8 + 0x40 + 8 * 8 + 0x40;
	int LG_SEQ = 4 * 120 * 2;

	/* Pattern */
	public static final int PATTERN_MEASURE_BYTE = 1;
	int INSTRUMENT_CHANNELS_PER_PATTERN = 15;
	int SINGLE_PATTERN_LENGTH = PATTERN_MEASURE_BYTE + INSTRUMENT_CHANNELS_PER_PATTERN + 5;

	int VARIATIONS_PER_PATTERN = 4;
	int FILL_INS_PER_PATTERN = 1;
	int ALL_VARIATIONS_PER_PATTERN = VARIATIONS_PER_PATTERN + FILL_INS_PER_PATTERN;

	int PATTERNS_COUNT = 8;

	int ALL_PATTERNS_COUNT = PATTERNS_COUNT * ALL_VARIATIONS_PER_PATTERN;
	int PATTERN_LENGTH = ALL_PATTERNS_COUNT * SINGLE_PATTERN_LENGTH;

	int PATTERN_WEIRD_GAP = 0x28;
	int PATTERN_END_GAP = 2;
	int PATTERN_MEASURE_END = 0xFF;

	int PATTERN_MEASURES_IS_MEASURE_MASK = 0b10000000;
	int PATTERN_NOTE_ACCENT_MASK = 0b01110000;
	int PATTERN_NOTE_CHANNEL_MASK = 0b00001111;

	/*  */

	int BULK_DUMP_BLOCK_HEADER_LENGTH = 6;

}
