package parser.constants;

public interface Constants {

	/* Pattern */
	int PATTERN_QUARTERS_PER_BAR_BYTE = 1;
	int INSTRUMENT_CHANNELS_PER_PATTERN = 15;
	int SINGLE_PATTERN_LENGTH = PATTERN_QUARTERS_PER_BAR_BYTE + INSTRUMENT_CHANNELS_PER_PATTERN + 5;

	int VARIATIONS_PER_PATTERN = 4;
	int FILL_INS_PER_PATTERN = 1;
	int ALL_VARIATIONS_PER_PATTERN = VARIATIONS_PER_PATTERN + FILL_INS_PER_PATTERN;

	int PATTERNS_COUNT = 8;

	int ALL_PATTERNS_COUNT = PATTERNS_COUNT * ALL_VARIATIONS_PER_PATTERN;
	int ALL_PATTERNS_LENGTH = ALL_PATTERNS_COUNT * SINGLE_PATTERN_LENGTH;

	// TODO test if gap still present, or was bug from older parser.
	// Length is 40, so this could match 5 variations * 8 patterns.
	int PATTERN_UNKNOWN_WEIRD_GAP = 0x28;

	// TODO unknown why there is this offset
	int PATTERN_UNKNOWN_OFFSET_BY_2 = 2;

	int PATTERN_END_GAP = 2;
	int PATTERN_MEASURE_END = 0xFF;

	int PATTERN_MEASURES_IS_MEASURE_MASK = 0b10000000;
	int PATTERN_NOTE_ACCENT_MASK = 0b01110000;
	int PATTERN_NOTE_ACCENT_SHIFT_RIGHT = 4;
	int PATTERN_NOTE_CHANNEL_MASK = 0b00001111;

	/*  */

}
